scripts y coverage

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -15,12 +15,17 @@ export PATH="$NPM_GLOBAL_DIR/bin:$PATH"
 # Ejecutar el build
 echo "Building the project..."
 
-if ! ./generate_mocks.sh; then
+if ! ./scripts/generate_mocks.sh; then
     echo "Build failed generating mocks."
     exit 1
 fi
 
-if ! ./generate_doc.sh; then
+if ! ./scripts/generate_gql.sh; then
+    echo "Build failed generating mocks."
+    exit 1
+fi
+
+if ! ./scripts/generate_doc.sh; then
     echo "Build failed generating docs."
     exit 1
 fi
@@ -39,6 +44,6 @@ if ! go test -v ./...; then
     exit 1
 fi
 
-./run_test_report.sh quiet
+./scripts/run_test_report.sh quiet
 
 echo "Build and tests passed. Proceeding with commit."
